### ISSUE TITLE
Consider the multi-apps explainer

### ISSUE THREAD

**Issue by michaelwasserman** [philloooo/pwa-unique-id#2]
Please consider the multi-apps explainer:
https://github.com/ivansandrk/multi-apps/blob/main/explainer.md

Perhaps multi-apps would want multiple ids? Perhaps some id schemas would at least make that possible in the future?
I'm not super familiar here, I'm mainly hoping that we'd get a broad view of what might be needed around each proposal.

**Comment by philloooo** [comment]
thanks, I took a look at that explainer, seem to make more sense to me to have one id for the multi-apps case, as there will be one manifest for a multi-apps PWA, thus the installation and update life cycle will treat it as one entity. We can continue the conversation on the issue you created there.

**Comment by michaelwasserman** [comment]
Acknowledged; sgtm. Feel free to reopen this issue as needed.

**Comment by dmurph** [comment]
FYI - I believe the current preferred solution is to not have one manifest and instead have one manifest per app, which would let us use all of our existing updating logic.

In my head I was imagining:

 * Sub apps will never be their own app,
 * We allow an app, in our database proto, to reference sub-app ids. (I guess maybe in sync data too)
 * Those sub-apps basically exist in our system as regular apps, but we store the parent id in the web app database proto (and in the sync data)
